sonar.organization=sarredondq-key
sonar.projectKey=ghactions-delivery-platform-web
sonar.projectName=ghactions-delivery-platform-web

sonar.sources=src/
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**
sonar.source.exclusions=src/__tests__/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=**/__tests__/**,**/test-setup.ts,**/main.tsx,**/vite-env.d.ts,**/vite.config.ts
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**
