sonar.organization=sarredondq
sonar.projectKey=sarredondq-ghactions
sonar.projectName=Delivery Platform Lab

sonar.sources=apps/
sonar.tests=apps/api/tests,apps/web/src/__tests__

sonar.javascript.lcov.reportPaths=apps/api/coverage/lcov.info,apps/web/coverage/lcov.info

sonar.coverage.exclusions=**/tests/**,**/__tests__/**,**/test-setup.ts,**/main.tsx,**/vite-env.d.ts,**/vite.config.ts
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**
